name: 🆙 Release

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    environment: Deployment
    runs-on: ubuntu-latest
    if: ${{ github.ref=='refs/heads/main' && github.event_name!='pull_request' }}

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: Install deps
          run: |
            python -m pip install pip --upgrade
            python -m pip install hatch githubrelease httpx==0.18.2 autopub


        - name: Check if we should release
          id: check_release
          run: |
            set +e
            echo ::set-output name=release::$(autopub check)
        - name: Publish
          if: steps.check_release.outputs.release == ''
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          run: |
            git remote set-url origin https://${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}
            autopub prepare
            hatch build
            autopub commit
            autopub githubrelease
            hatch publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
